### PR TITLE
Adding minimized images, updating mobile background, updating spacing on...

### PR DESCRIPTION
**Pull request by pcsandford**
... larger resolutions

@mmeiers I have reduced the size of the images so they should load up faster. I have also worked on increasing the number of viewable slides. I was thinking of adding in the background that is in the Events template to use as the background for the 'closed' state of the main desktop menu and wanted to know your thoughts on this? Thanks!

### CODE REVIEW

**Comment by mmeiers** [comment]
@pcsandford 
I think the actual Events template (the first template) in the list should be playing when the demo app first starts up. I may have failed to mention this before but ultimately the app should auto rotate through the list of all the templates in a  timed fashion. (the old one does this)

**Comment by pcsandford** [comment]
@mmeiers  Ah, ok, so auto rotate that will cut out when the user selects a thumbnail from navigation menu? Then should it auto rotate again after a period of inactivity? 

I will merge this PR for now and get working on that first thing in the morning. Thanks!

**Comment by mmeiers** [comment]
@pcsandford Correct, it should rotate after inactivity.
I do have some small layout/alignment feedback but I suppose Ill wait on that until you feel its done.

**Comment by pcsandford** [comment]
cool, thanks @mmeiers I am working on the js this morning to get that functionality up and running and will make a new PR as soon as it is done. I think the current PR should have some alignment changes so it will be good to hear what you think. Thanks!

**Pull request merged**
